services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/share:/mnt/share:ro
    environment:
      - DB_HOST=db
      - DB_USER=file_share_user
      - DB_PASS=P@ssw0rd
      - DB_NAME=file_share
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=file_share
      - MYSQL_USER=file_share_user
      - MYSQL_PASSWORD=P@ssw0rd
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/lab.demo.crt:/etc/nginx/certs/lab.demo.crt:ro
      - ./certs/lab.demo.key:/etc/nginx/certs/lab.demo.key:ro
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
